### ISSUE TITLE
Creating the same tuple should return an error

### ISSUE THREAD

**Issue by omerlh** [ory/keto#1011] opened 2022-09-08 04:50 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am using the admin API to create a tuple. I would expecting that calling the same API with the same tuple would result in error, but instead a new tuple is created, identical to the one I already created before.

### Reproducing the bug

This is the API call I am using:

```
PUT /admin/relation-tuples
{"namespace":"rules","object":"c3251c8e-d4c8-42a2-ad6d-355bb020f1d0","subject_set":{"namespace":"integration","object":"75f10a13-eaf2-4cb2-8233-d1c4dd73126c","relation":"#"},"relation":"child"}
```

### Version

cloud

**Comment by zepatrik** [comment] 2022-10-27 13:57
Duplicate of #292. There is an explanation for this behavior as well.

**Closed by zepatrik** 2022-10-27 13:57 UTC
Labels: bug
