### ISSUE TITLE
Importing github.com/ory/keto not compatible with Kratos version 0.6.x

### ISSUE THREAD

**Issue by janiskemper** [ory/keto#612] opened 2021-05-31 19:08 UTC
**Describe the bug**

When importing Keto we need to do the same replacements that are currently in master branch and in version v0.6.0. 

However, the replacement for kratos-client-go is on version v0.5.4-alpha.1.0.20210210170256-960b093d8bf9 which is not compatible with latest Kratos version.

When removing this replacement the error

```
go: github.com/ory/keto@v0.6.0-alpha.3 requires
        github.com/ory/cli@v0.0.49 requires
        github.com/ory/kratos@v0.5.5-alpha.1.0.20210319103511-3726ed4d145a requires
        github.com/ory/cli@v0.0.41 requires
        github.com/ory/kratos@v0.5.5-alpha.1.0.20210210153145-e5a863030890 requires
        github.com/ory/kratos-client-go@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
        
```
occurs. As long as the replacement is there, it is obviously not possible to update kratos-client-go.

**Reproducing the bug**

Just have a Go project importing ```github.com/ory/keto v0.6.0-alpha.3```, use the replacements (otherwise it's not working anyway) and then try to use kratos-client-go on its latest version.

**Expected behavior**

It should be possible to use latest Kratos (0.6.x) and Keto (0.6.x) version together.

**Comment by aeneasr** [comment] 2021-06-02 11:53
For details see https://github.com/ory/kratos/issues/1363

**Comment by zepatrik** [comment] 2021-06-21 10:04
Should be closed by #619

**Closed by zepatrik** 2021-06-21 10:04 UTC

**Comment by janiskemper** [comment] 2021-06-24 07:24
@zepatrik is it possible to make use of your PR? I get an error if I try go get of the latest verified commit:
```
go get github.com/ory/keto@5172ba4e2a0ae76b56d29e924ae8a95131905f4a
go: github.com/ory/keto@v0.6.0-alpha.3 requires
        github.com/ory/cli@v0.0.49 requires
        github.com/ory/kratos@v0.5.5-alpha.1.0.20210319103511-3726ed4d145a requires
        github.com/ory/kratos/corp@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by zepatrik** [comment] 2021-06-28 14:26
Hm I cannot reproduce your error, but I get
```
$ go get github.com/ory/keto@5172ba4e2a0ae76b56d29e924ae8a95131905f4a
go: downloading github.com/ory/keto v0.6.0-alpha.3.0.20210623065416-5172ba4e2a0a
go get: github.com/ory/keto@v0.5.7-alpha.1.pre.0 updating to
	github.com/ory/keto@v0.6.0-alpha.3.0.20210623065416-5172ba4e2a0a requires
	github.com/ory/keto/proto@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```
which is also not ideal :sweat_smile:

**Comment by janiskemper** [comment] 2021-06-28 14:30
I tried it earlier today again and got the same error as you. My go version is ```go version go1.16.4 linux/amd64```

**Comment by zepatrik** [comment] 2021-06-28 14:53
Ok so I guess we can fix that by putting the latest release into the `go.mod` but that will have to be automated. WDYT @aeneasr 

For me, the following `go.mod` works:

```go.mod
module foo.com/bar

go 1.16

replace github.com/oleiade/reflections => github.com/oleiade/reflections v1.0.1

replace github.com/ory/keto/proto => github.com/ory/keto/proto 5172ba4e2a0ae76b56d29e924ae8a95131905f4a

require github.com/ory/keto 5172ba4e2a0ae76b56d29e924ae8a95131905f4a
```

**Comment by zepatrik** [comment] 2021-06-28 14:59
But maybe it is better to keep the current, invalid version. That way, we can never make a mistake because one would always have to add a replace statement. It is not ideal, but why would you use keto as a dependency in the first place?

**Comment by janiskemper** [comment] 2021-06-28 15:01
Isn't this the way to go for using it with gRPC? According to the docs at least where https://github.com/ory/keto/tree/master/proto/ory/keto/acl seems to be the gRPC SDK

**Comment by zepatrik** [comment] 2021-06-28 15:02
Ah yes, but you can just import `github.com/ory/keto/proto` then, without the top level module.
At least that's what I intended there :sweat_smile:

**Comment by zepatrik** [comment] 2021-06-28 15:10
Ok so this works for me:
```
$ cat go.mod
module foo.com/bar

go 1.16

require github.com/ory/keto/proto v0.0.0-20210625115946-94d46194656c
$ cat main.go 
package main

import _ "github.com/ory/keto/proto/ory/keto/acl/v1alpha1"
```
and I think that should be the way to go?
We definitely should add that to the docs.

**Comment by janiskemper** [comment] 2021-06-28 15:25
That is indeed useful information :D I could have figured that out on my own, but didn't really think about this possibility tbh...
That's very helpful, thank you! And yes, explicit docs could make lives easier for others here!
