### ISSUE TITLE
Keto is posting plain text passwords when there is an issue with DSN

### ISSUE THREAD

**Issue by from-nibly** [ory/keto#237] opened 2020-08-31 20:56 UTC
**Describe the bug**

If ory keto can't parse the DSN value it logs the entire thing (including the database password) in plain text. I'm not seeing a way to add a database password without passing it to the DSN variable. What am I missing here?  If this is the preferred way to give keto the password then keto should definitely not be logging the value ever.

**Reproducing the bug**

Set DSN to anything unparsable by keto

_Server logs_

```
time="2020-08-31T20:47:31Z" level=info msg="Retrying in 1.000000 seconds..."
time="2020-08-31T20:47:32Z" level=info msg="Establishing connection with SQL database backend" dsn="postgres://*:*@postgres:5432/<value here>?sslmode=disable%0A"
time="2020-08-31T20:47:32Z" level=error msg="Unable to ping SQL database backend" dsn="postgres://*:*@postgres:5432/p<value here>?sslmode=disable%0A" error="cannot parse `postgres://<value here>:<The actual password!>@postgres:5432/<value here>?sslmode=disable%0A`: failed to configure TLS (sslmode is invalid)"
time="2020-08-31T20:47:32Z" level=error msg="Unable to connect to database, retrying..." error="could not ping SQL connection: cannot parse `postgres://<value here>:<The actual password!>@postgres:5432/<value here>?sslmode=disable%0A`: failed to configure TLS (sslmode is invalid)"
time="2020-08-31T20:47:32Z" level=info msg="Retrying in 1.000000 seconds...
```
_Server configuration_

`postgres://<value here>:<The actual password!>@postgres:5432/<value here>?sslmode=disable%0A`

**Expected behavior**

Not log the full DSN ever. Also maybe it should be considered to not pass in an entire url as the DSN rather pass individual values in.
**Environment**

- Version: oryd/keto:v0.5.6-alpha.1
- Docker

**Comment by aeneasr** [comment] 2020-08-31 20:57
Should definitely not happen, I think this should be resolved in ory/x for quite a while but it might be needed to update the dependencies. Would you be up for a PR?

**Comment by from-nibly** [comment] 2020-08-31 21:00
> Would you be up for a PR?

Do you mean, am I able to make the fix? Probably not I'm strapped with my current workload.

**Comment by aeneasr** [comment] 2020-08-31 21:00
Yes, that was the question :)

**Comment by from-nibly** [comment] 2020-08-31 21:11
Something like this should probably be done to set the password as a special type that gets auto redacted so it can't be forgotten. https://github.com/op/go-logging

**Comment by aeneasr** [comment] 2020-08-31 21:13
We're no longer using a URL parser to parse those but I think Keto still might to that. The problem is that DSNs for all database differ quite a lot (e.g. MySQL's `miysql://foo:bar@tcp(...)` syntax or SQLite's `:file:` syntax) which makes it tricky, but yeah, this still shouldn't happen.

**Comment by aeneasr** [comment] 2021-02-09 14:58
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.

**Closed by aeneasr** 2021-02-09 14:58 UTC
Labels: bug, help wanted
