### ISSUE TITLE
Upgrade from < 1.0.0-beta Hydra migration commands fail

### ISSUE THREAD

**Issue by ionutzp** [ory/keto#23] opened 2018-06-11 15:32 UTC
From: https://github.com/ory/hydra/blob/master/UPGRADE.md#access-control--warden-api
```
# Migrate the policies and warden groups to keto
$ keto migrate hydra $DATABASE_URL

# Create other Keto database schemas
$ keto migrate sql $DATABASE_URL
```
Error output: 
```
keto_1            | INFO[0000] Successfully applied SQL migrations           migrations=0 table=role
keto_1            | FATA[0000] An error occurred while trying to apply SQL migrations  error="Could not migrate sql schema, applied 2 migrations: pq: relation "ladon_subject_compiled_idx" already exists handling 3" migrations=0 table=policies
```

**Comment by arekkas** [comment] 2018-06-11 20:54
So the problem is merely a simple typo. The migration table (from `migrate hydra ...`) is properly moved to `keto_policy_migration` but the code executing the policy migrations itself (from `migrate sql`) uses the plural form `keto_policy_migrations`. As that table doesn't exist, it re-applies the migrations which then fails due to duplicate statements.

This will be fixed in the next release.

**Closed** 2018-06-11 21:15 UTC
Labels: bug
