### ISSUE TITLE
Keto latency with large number of policies

### ISSUE THREAD

**Issue by jrmullins** [ory/keto#104] opened 2019-05-08 18:16 UTC
**Describe the bug**
Keto's latency increases with policies and resources

**To Reproduce**
1. (Optionally) Start with a fresh database
2. Create 30k regex policies with 1 or more resources
3. Perform `allowed` checks
4. Witness requests take 1-10 seconds to complete

**Expected behavior**
Access allowed checks under 100ms

**Version:**
 - Environment: MacOS Mojave, Postgres 11
 - Version: Master (0.3.1)

**Additional context**
Initially, I noticed Keto requests taking longer than 1 minute in pods running on Kubernetes when our policy count exceeded 30k. We also had memory issues but it may be unrelated. I was unable to run a memory profile using ppof on our images, the pod would crash OOM before the memory profile was written.

The policy causing the latency had 16 resources. They all had 2 wildcards.
Ex: `tenant:<.*>:resource:foo<.*>`

Observations about latency:
- The number of resources directly affects latency. 
- The number of policies (unused or not) affects latency
- `SERVE_MAX_AGE` caused 500 errors with this many policies

A temporary solution to this would be to split my policy into 16 individual policies, but 1-2 second requests (running locally) still seems extreme.

**Comment by jrmullins** [comment] 2019-05-08 18:17
Here was my reproduction code that I was running locally, nothing fancy.
```
package main

import (
	"fmt"
	"math/rand"
	"net/http"
	"strconv"
	"time"

	"github.com/ory/keto/sdk/go/keto"
	"github.com/ory/keto/sdk/go/keto/swagger"
)

func main() {
	// ensure keto is running
	res, err := http.Get("http://localhost:4466/health/ready")
	if err != nil {
		panic(err)
	}
	if res.StatusCode != 200 {
		panic("Keto not ready")
	}
	defer res.Body.Close()

	sdk, err := keto.NewCodeGenSDK(&keto.Configuration{
		EndpointURL: "http://localhost:4466",
	})

	if err != nil {
		panic(err)
	}

	// Create 30k policies
	for i := 0; i < 1; i++ {
		createPolicy(sdk, strconv.Itoa(i))
	}
	fmt.Println("Policies created.")

	// Create some workers to simulate humans
	for i := 0; i < 15; i++ {
		go work(sdk)
	}
	fakeChan := make(chan bool)
	<-fakeChan // wait forever

}

func work(sdk *keto.CodeGenSDK) {
	for {
		randInt := strconv.Itoa(rand.Int())

		_, resp, err := sdk.DoOryAccessControlPoliciesAllow("regex", swagger.OryAccessControlPolicyAllowedInput{
			Subject:  "tenant:" + randInt + ":user:" + randInt,
			Action:   "check",
			Resource: "tenant:" + randInt + ":thing0:" + randInt,
		})
		if err != nil {
			panic(err)
		}
		if resp.StatusCode != 200 {
			fmt.Println("Status code: ", resp.StatusCode)
			panic("Bad status code")
		}

		r := rand.Intn(10)
		time.Sleep(time.Duration(r) * time.Second)
		fmt.Printf(".")

	}
}

func createPolicy(sdk *keto.CodeGenSDK, id string) *swagger.APIResponse {
	_, resp, err := sdk.UpsertOryAccessControlPolicy("regex", swagger.OryAccessControlPolicy{
		Id:       id,
		Subjects: []string{"tenant:<.*>:user:<.*>"},
		Resources: []string{
			"tenant:<.*>:thing" + id + ":<.*>",
			"tenant:<.*>:foo" + id + ":<.*>",
			"tenant:<.*>:bar" + id + ":<.*>",
			"tenant:<.*>:baz" + id + ":<.*>",
			"tenant:<.*>:boo" + id + ":<.*>",
			"tenant:<.*>:bam" + id + ":<.*>",
			"tenant:<.*>:bag" + id + ":<.*>",
			"tenant:<.*>:bad" + id + ":<.*>",
		},
		Actions: []string{"check"},
		Effect:  "allow",
	})
	if err != nil {
		panic(err)
	}
	if resp.StatusCode != 200 {
		panic("policy not inserted")
	}
	return resp
}
```

**Comment by aeneasr** [comment] 2019-05-09 08:43
Just for clarification - `SERVE_MAX_AGE ` is not a valid configuration entity so just wanted to check if that is really causing any issues? Where you maybe refering to `SERVE_CORS_MAX_AGE`?

**Comment by aeneasr** [comment] 2019-05-09 09:04
Also, the SDK is pre-0.3.0 (generated by swagger-codegen) - this shouldn't have an impact, I'm however trying to minimize potential reproduction issues :)

**Comment by aeneasr** [comment] 2019-05-09 09:53
Ok, so I've been able to reproduce this issue with [the following code](https://github.com/ory/keto/commit/6e26b542d0f0a30418122866d0d47f18d7b4add8). There are actually two combinations where we see long execution times:

- high velocity [`time.Sleep(time.Millisecond)`](https://github.com/ory/keto/commit/6e26b542d0f0a30418122866d0d47f18d7b4add8#diff-48408b498d1a54ff23092c4f62db2c85R40) with few policies [`i  < 1`](https://github.com/ory/keto/commit/6e26b542d0f0a30418122866d0d47f18d7b4add8#diff-48408b498d1a54ff23092c4f62db2c85R21)
- low velocity [`time.Sleep(time.Second)`](https://github.com/ory/keto/commit/6e26b542d0f0a30418122866d0d47f18d7b4add8#diff-48408b498d1a54ff23092c4f62db2c85R40) with many policies [`i  < 30000`](https://github.com/ory/keto/commit/6e26b542d0f0a30418122866d0d47f18d7b4add8#diff-48408b498d1a54ff23092c4f62db2c85R21)

In both scenarios it is possible to reproduce long requests (sometimes even canceled requests) and high CPU load. However, only the second case leads to high memory consumption.

Here is a log output for a request that canceled execution:

```
INFO[0148] completed handling request                    measure#keto.latency=41340073178 method=POST remote="[::1]:61701" request=/engines/acp/ory/regex/allowed status=200 text_status=OK took=41.340073178s
ERRO[0148] An error occurred while handling a request    code=500 debug= details="map[]" error="eval_cancel_error: caller cancelled query execution" reason= request-id= status= trace="Stack trace: \ngithub.com/ory/keto/engine.(*Engine).eval\n\t/Users/foobar/workspaces/go/src/github.com/ory/keto/engine/engine.go:71\ngithub.com/ory/keto/engine.(*Engine).Evaluate.func1\n\t/Users/foobar/workspaces/go/src/github.com/ory/keto/engine/engine.go:44\ngithub.com/julienschmidt/httprouter...................." writer=JSON
```

The CPU profile is at: [profile001.pdf](https://github.com/ory/keto/files/3161379/profile001.pdf)

The memory profile is at: [profile003.pdf](https://github.com/ory/keto/files/3161414/profile003.pdf)

**Comment by aeneasr** [comment] 2019-05-09 09:56
I did some further debugging and noticed that even an empty policy cache will leave to long response times (5s+) with a high velocity configuration for all flavors (exact, regexp, glob).

**Comment by aeneasr** [comment] 2019-05-09 09:58
Upgrading to OPA v0.10.7 did not change anything.

**Comment by aeneasr** [comment] 2019-05-09 10:06
God I'm stupid, I forgot to divide the total time running by the count so the results I saw were not the average but the total 🤦‍♂ . Let's start a-fresh!

**Comment by aeneasr** [comment] 2019-05-09 10:16
All tests are running the in-memory database

* Without re-creating the engine store every time (empty store):
  * exact: `INFO[0011] Took 0.03206112s to on average for worker 0 `
  * glob: `INFO[0010] Took 0.00560281s to on average for worker 3`
  * regex: `INFO[0010] Took 0.00584743s to on average for worker 1`
* With re-creating the engine store every time (store with 5 policies):
  * exact: `INFO[0010] Took 0.01129659s to on average for worker 7`
  * glob: `INFO[0010] Took 0.01081094s to on average for worker 6`
  * regex: `INFO[0010] Took 0.00616241s to on average for worker 0`

Therefore my initial assumption is showing as being probably the root cause of this issue. The problem is that we're re-creating the rego store (which contains those 30k policies) on every call to `/allowed`. The internals involve [de/encoding things in memory](https://github.com/ory/keto/blob/master/storage/manager.go#L37-L84) causing a lot of memory allocations and probably also causing OPA to be unable to cache certain things which then makes sense that keto becomes quite slow when we have a lot of data that needs to be handled there.

**Comment by aeneasr** [comment] 2019-05-09 10:38
I wrote a really dumb caching mechanism which basically creates the rego store only once (with 30k policies) and re-ran the perf tool. It halfed the time to serve requests but there's still room for improvement.

**Comment by jrmullins** [comment] 2019-05-14 13:04
@aeneasr  Did you check the caching in anywhere? I'd love to test it locally and don't see it on the perf branch.

**Comment by aeneasr** [comment] 2019-05-20 09:37
@jrmullins sorry for the late reply - yeah it was checked in but it wasn't thread safe or anything which is why I reverted the changes. It was basically just to see if that's the root cause of the performance issues or not (it is, but not exclusively).

**Comment by aeneasr** [comment] 2019-05-20 13:44
So I did some further digging and it appears that this is caused (most likely) by the way we defined the rego policies. I get similar slow queries/responses when using vanilla OPA.

**Comment by aeneasr** [comment] 2019-05-20 14:44
This has now been moved upstream: https://github.com/open-policy-agent/opa/issues/1443

**Comment by aeneasr** [comment] 2019-05-20 17:31
Possibly related: https://github.com/open-policy-agent/opa/issues/1434

**Comment by elwinar** [comment] 2019-06-04 10:32
Hello there. Any news on this? 

I'm currently evaluating the possibility of using _Keto_ at work and the performances are just terrible with the number of policies we have to handle (about 100K resources split in 10K groups for 35K users in 2K customers).

Admittedly, I'm still fumbling around with the best way to define policies, but I'm concerned that I'm climbing to 4.5s/request with my current benchmark (25 concurrent workers with _siege_).

I'm willing to help if needed (if only to get a better understanding of the solution), and I can actually provide an export of my policies if that can help.

**Comment by aeneasr** [comment] 2019-06-04 10:34
Please follow progress at https://github.com/open-policy-agent/opa/issues/1443

Unless we switch the decision engine (unlikely within the next 3-6 months) we can't fix this issue on our end.

**Comment by jrmullins** [comment] 2019-06-27 17:57
Looks like OPA merged some code for glob matching. Assuming the performance increases, this would be fine for our use case as the majority of our policies are not that complex.

**Comment by aeneasr** [comment] 2019-06-28 13:14
Ok, we'll create a patch as soon as they release a new version! If you want, you could test performance by setting the opa dependency in `go.mod` of keto to master.

**Comment by aeneasr** [comment] 2019-06-28 13:15
However, unless there is significant progress made in OPA, I believe that we will move back to our own engine at some point.

**Comment by aeneasr** [comment] 2019-07-12 12:07
@jrmullins did you by any chance do what I suggested in https://github.com/ory/keto/issues/104#issuecomment-506729408 ?

**Comment by jrmullins** [comment] 2019-07-19 12:13
Sorry for the delay, I have been swamped at work. I'm hoping to take a look at this soon.

**Comment by jrmullins** [comment] 2019-07-23 22:13
I switched my benchmark tests to use glob policies, got the latest OPA (0.12.1) via `go get github.com/open-policy-agent/opa@master`, `go mod vendor` from my keto repo, restarted Keto running off a new postgres database, and reran my performance testing. 

Unfortunately, I did not see any difference in performance. I still saw latency spike to 7 seconds after an initial period of it running fine more 30 seconds. 

@aeneasr Was there something else I could have done to the policies themselves to make the partial evaluation match faster?

**Comment by aeneasr** [comment] 2021-02-09 14:57
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.

ps: We optimized the refactoring for speed, so this will never happen again!

**Closed by aeneasr** 2021-02-09 14:57 UTC
Labels: bug, help wanted
