### ISSUE TITLE
REST API create and subsequent get relation does not properly persist fields

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#291] opened 2020-11-10 12:35 UTC
**Describe the bug**

See below

**Reproducing the bug**

```shell script
$ curl --location --request PUT 'http://localhost:4466/relations' \
--header 'Content-Type: application/json' \
--data-raw '{
	"object": {
		"id": "amorevino",
		"namespace": "tenants"
	},
	"relation": "write",
	"subject": {
		"id": "aeneas"
	}
}'

$ curl --location --request GET 'http://localhost:4466/relations'
[
    {
        "object": {
            "id": "",
            "namespace": ""
        },
        "relation": "write",
        "subject": {
            "id": ""
        }
    }
]
```

**Comment by zepatrik** [comment] 2021-03-08 14:30
Ok so this seems fixed now, could not reproduce anymore:

```bash
$ curl --location --request PUT 'http://localhost:4467/relationtuple' --header 'Content-Type: application/json' --data-raw '{
"object": "amorevino",
"namespace": "tenants",
"relation": "write",
"subject": "aeneas"
}'

curl --location --request GET 'http://localhost:4466/relationtuple?namespace=tenants' | jq
{
  "relation_tuples": [
    {
      "namespace": "tenants",
      "object": "amorevino",
      "relation": "write",
      "subject": "aeneas"
    }
  ],
  "next_page_token": "no other page",
  "is_last_page": true
}
```

**Closed by zepatrik** 2021-03-08 14:30 UTC
Labels: bug, corp/m5
