### ISSUE TITLE
Dataloss Bug

### ISSUE THREAD

**Issue by nburns** [ory/keto#1085] opened 2022-10-20 16:47 UTC
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

 I'm creating a tuple with one object ('hire') and deleting a tuple with a different object ('retain') (BUT the other fields are the same) and the first tuple is being deleted, which is not what I'd expect.

Description of the issue with relation tuple syntax:
```
create products:hire#read@user-621166 -> ok
check products:hire#read@user-621166 -> allowed = true
delete products:retain#read@user-621166 -> ok (note we're deleting a different tuple the object is different)
check products:hire#read@user-621166 -> allowed = false (this should still be true)
```

### Reproducing the bug

Run the following script:
```bash
#!/usr/bin/env bash
set -x
curl -v -X PUT http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "hire", "relation": "read", "subject_id": "user-621166"}'
curl -v 'http://localhost:4468/relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166'
curl -v -X DELETE http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "retain", "relation": "read", "subject_id": "user-621166"}'
curl -v 'http://localhost:4468/relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166'
```

output:
```
+ curl -v -X PUT http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "hire", "relation": "read", "subject_id": "user-621166"}'
*   Trying 127.0.0.1:4469...
* Connected to localhost (127.0.0.1) port 4469 (#0)
> PUT /admin/relation-tuples HTTP/1.1
> Host: localhost:4469
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 92
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Content-Type: application/json; charset=utf-8
< Location: /relation-tuples?namespace=products&object=hire&relation=read&subject_id=user-621166
< Date: Thu, 20 Oct 2022 16:27:08 GMT
< Content-Length: 86
<
{"namespace":"products","object":"hire","relation":"read","subject_id":"user-621166"}
* Connection #0 to host localhost left intact
+ curl -v 'http://localhost:4468/relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166'
*   Trying 127.0.0.1:4468...
* Connected to localhost (127.0.0.1) port 4468 (#0)
> GET /relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166 HTTP/1.1
> Host: localhost:4468
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Thu, 20 Oct 2022 16:27:08 GMT
< Content-Length: 17
<
{"allowed":true}
* Connection #0 to host localhost left intact
+ curl -v -X DELETE http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "retain", "relation": "read", "subject_id": "user-621166"}'
*   Trying 127.0.0.1:4469...
* Connected to localhost (127.0.0.1) port 4469 (#0)
> DELETE /admin/relation-tuples HTTP/1.1
> Host: localhost:4469
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 94
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Thu, 20 Oct 2022 16:27:08 GMT
<
* Connection #0 to host localhost left intact
+ curl -v 'http://localhost:4468/relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166'
*   Trying 127.0.0.1:4468...
* Connected to localhost (127.0.0.1) port 4468 (#0)
> GET /relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166 HTTP/1.1
> Host: localhost:4468
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Thu, 20 Oct 2022 16:27:08 GMT
< Content-Length: 18
<
{"allowed":false}
* Connection #0 to host localhost left intact
sync-access-to-keto nick@worky ~/c/workstep> ./keto-bug.sh &| pbcopy
sync-access-to-keto nick@worky ~/c/workstep> ./keto-bug.sh
+ curl -v -X PUT http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "hire", "relation": "read", "subject_id": "user-621166"}'
*   Trying 127.0.0.1:4469...
* Connected to localhost (127.0.0.1) port 4469 (#0)
> PUT /admin/relation-tuples HTTP/1.1
> Host: localhost:4469
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 92
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Content-Type: application/json; charset=utf-8
< Location: /relation-tuples?namespace=products&object=hire&relation=read&subject_id=user-621166
< Date: Thu, 20 Oct 2022 16:28:15 GMT
< Content-Length: 86
<
{"namespace":"products","object":"hire","relation":"read","subject_id":"user-621166"}
* Connection #0 to host localhost left intact
+ curl -v 'http://localhost:4468/relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166'
*   Trying 127.0.0.1:4468...
* Connected to localhost (127.0.0.1) port 4468 (#0)
> GET /relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166 HTTP/1.1
> Host: localhost:4468
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Thu, 20 Oct 2022 16:28:15 GMT
< Content-Length: 17
<
{"allowed":true}
* Connection #0 to host localhost left intact
+ curl -v -X DELETE http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "retain", "relation": "read", "subject_id": "user-621166"}'
*   Trying 127.0.0.1:4469...
* Connected to localhost (127.0.0.1) port 4469 (#0)
> DELETE /admin/relation-tuples HTTP/1.1
> Host: localhost:4469
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 94
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Date: Thu, 20 Oct 2022 16:28:15 GMT
<
* Connection #0 to host localhost left intact
+ curl -v 'http://localhost:4468/relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166'
*   Trying 127.0.0.1:4468...
* Connected to localhost (127.0.0.1) port 4468 (#0)
> GET /relation-tuples/check/openapi?namespace=products&object=hire&relation=read&subject_id=user-621166 HTTP/1.1
> Host: localhost:4468
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Thu, 20 Oct 2022 16:28:15 GMT
< Content-Length: 18
<
{"allowed":false}
* Connection #0 to host localhost left intact
```

Notice how the last result is `{"allowed":false}` when it should be `{"allowed":true}` since the tuple being deleted has a different object (`retain` not `hire`)

### Relevant log output

```shell
time=2022-10-20T09:27:08-07:00 level=info msg=started handling request http_request=map[headers:map[accept:*/* content-length:92 content-type:application/x-www-form-urlencoded user-agent:curl/7.79.1] host:localhost:4469 method:PUT path:/admin/relation-tuples query:<nil> remote:127.0.0.1:56209 scheme:http]
time=2022-10-20T09:27:08-07:00 level=debug msg=creating relation tuple audience=application namespace=products object=hire relation=read service_name=Ory Keto service_version=v0.10.0-alpha.0 subject_id=user-621166
time=2022-10-20T09:27:08-07:00 level=info msg=completed handling request http_request=map[headers:map[accept:*/* content-length:92 content-type:application/x-www-form-urlencoded user-agent:curl/7.79.1] host:localhost:4469 method:PUT path:/admin/relation-tuples query:<nil> remote:127.0.0.1:56209 scheme:http] http_response=map[headers:map[content-type:application/json; charset=utf-8 location:/relation-tuples?namespace=products&object=hire&relation=read&subject_id=user-621166] size:86 status:201 text_status:Created took:6.486625ms]
time=2022-10-20T09:27:08-07:00 level=info msg=started handling request http_request=map[headers:map[accept:*/* user-agent:curl/7.79.1] host:localhost:4468 method:GET path:/relation-tuples/check/openapi query:namespace=products&object=hire&relation=read&subject_id=user-621166 remote:127.0.0.1:56210 scheme:http]
time=2022-10-20T09:27:08-07:00 level=info msg=completed handling request http_request=map[headers:map[accept:*/* user-agent:curl/7.79.1] host:localhost:4468 method:GET path:/relation-tuples/check/openapi query:namespace=products&object=hire&relation=read&subject_id=user-621166 remote:127.0.0.1:56210 scheme:http] http_response=map[headers:map[content-type:application/json; charset=utf-8] size:17 status:200 text_status:OK took:3.053708ms]
time=2022-10-20T09:27:08-07:00 level=info msg=started handling request http_request=map[headers:map[accept:*/* content-length:94 content-type:application/x-www-form-urlencoded user-agent:curl/7.79.1] host:localhost:4469 method:DELETE path:/admin/relation-tuples query:<nil> remote:127.0.0.1:56211 scheme:http]
time=2022-10-20T09:27:08-07:00 level=debug msg=deleting relation tuples audience=application service_name=Ory Keto service_version=v0.10.0-alpha.0
time=2022-10-20T09:27:08-07:00 level=info msg=completed handling request http_request=map[headers:map[accept:*/* content-length:94 content-type:application/x-www-form-urlencoded user-agent:curl/7.79.1] host:localhost:4469 method:DELETE path:/admin/relation-tuples query:<nil> remote:127.0.0.1:56211 scheme:http] http_response=map[headers:map[] size:0 status:204 text_status:No Content took:3.932292ms]
time=2022-10-20T09:27:08-07:00 level=info msg=started handling request http_request=map[headers:map[accept:*/* user-agent:curl/7.79.1] host:localhost:4468 method:GET path:/relation-tuples/check/openapi query:namespace=products&object=hire&relation=read&subject_id=user-621166 remote:127.0.0.1:56212 scheme:http]
time=2022-10-20T09:27:08-07:00 level=info msg=completed handling request http_request=map[headers:map[accept:*/* user-agent:curl/7.79.1] host:localhost:4468 method:GET path:/relation-tuples/check/openapi query:namespace=products&object=hire&relation=read&subject_id=user-621166 remote:127.0.0.1:56212 scheme:http] http_response=map[headers:map[content-type:application/json; charset=utf-8] size:18 status:200 text_status:OK took:3.271ms]
```

### Relevant configuration

```yml
dsn: postgresql://keto-test@localhost/keto_test

log:
  level: debug
  leak_sensitive_values: true

serve:
  read:
    host: 0.0.0.0
    port: 4468

  write:
    host: 0.0.0.0
    port: 4469

namespaces:
  - id: 0
    name: products

  - id: 10
    name: facilities

  - id: 20
    name: positions
```

### Version

v0.10.0-alpha.0, 52259a30d0be0257f1bb7ef591ae769808450230

### On which operating system are you observing this issue?

macOS

### Additional Context

originally reported here: https://ory-community.slack.com/archives/C012RBZFMDG/p1666222984368799

**Comment by zepatrik** [comment] 2023-08-02 12:49
I cannot reproduce this. I could also not when this issue was created, but coming back to this because of other reports.
I am running this script now for minutes already, with no result. Same setup as you have.

```bash
function assert() {
  if [ "$1" != "$2" ]; then
    echo "Assertion failed: $1 != $2"
    exit 1
  fi
}

function execute() {
    assert "$(curl -X PUT http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "hire", "relation": "read", "subject_id": "user-621166"}'  -w "%{http_code}" -o /dev/null -s)" "201"
    assert "$(curl -X PUT http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "retain", "relation": "read", "subject_id": "user-621166"}'  -w "%{http_code}" -o /dev/null -s)" "201"
    assert "$(curl 'http://localhost:4468/relation-tuples/check?namespace=products&object=hire&relation=read&subject_id=user-621166'  -w "%{http_code}" -o /dev/null -s)" "200"
    assert "$(curl -X DELETE 'http://localhost:4469/admin/relation-tuples?namespace=products&object=retain&relation=read&subject_id=user-621166'  -w "%{http_code}" -o /dev/null -s)" "204"
    assert "$(curl 'http://localhost:4468/relation-tuples/check?namespace=products&object=hire&relation=read&subject_id=user-621166'  -w "%{http_code}" -o /dev/null -s)" "200"
}

while true; do
  execute &
  execute &
  execute &
  sleep 0.1
done
```
Any other ideas how this can be reliably reproduced?

**Comment by nburns** [comment] 2023-08-02 17:47
If you do a delete with the params in the body instead of the url it will delete all tuples

**Comment by hperl** [comment] 2023-08-03 07:28
Hi, and thanks for the report!

A similar issue has been reported and was fixed in https://github.com/ory/keto/commit/195182c37328cb7803b593cc73444c00cab76a7d. I could not reproduce your issues neitehr with the current master of Keto nor with Ory Permissons on Ory Network.

In short, the current behaviour is to require at least the `namespace` be set through the query parameters. So your example of

```sh
curl -v -X DELETE http://localhost:4469/admin/relation-tuples --data '{"namespace": "products", "object": "retain", "relation": "read", "subject_id": "user-621166"}'
```

will now return a `400 Bad Request` because no query parameters were specified.


Please feel free to re-open this issue if I missed anything.

**Closed by hperl** 2023-08-03 07:28 UTC
Labels: bug
